/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.ControleUsuario;
import javax.swing.JOptionPane;
import modelo.ModeloUsuario;

public class FormUsuario extends javax.swing.JFrame {

    ModeloUsuario mod = new ModeloUsuario();
    ControleUsuario control = new ControleUsuario();
    int flag = 0;
    
    public FormUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonNovoUsuario = new javax.swing.JButton();
        jButtonSalvarUsuario = new javax.swing.JButton();
        jButtonCancelarUsuario = new javax.swing.JButton();
        jButtonAlterarUsuario = new javax.swing.JButton();
        jButtonExcluirUsuario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        jTextFieldLoginUsuario = new javax.swing.JTextField();
        jPasswordSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordFieldConfirmaSenha = new javax.swing.JPasswordField();
        jTextFieldBuscarUsuario = new javax.swing.JTextField();
        jButtonBuscarUsuario = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIdUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonNovoUsuario.setText("Novo");
        jButtonNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoUsuarioActionPerformed(evt);
            }
        });

        jButtonSalvarUsuario.setText("Salvar");
        jButtonSalvarUsuario.setEnabled(false);
        jButtonSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarUsuarioActionPerformed(evt);
            }
        });

        jButtonCancelarUsuario.setText("Cancelar");
        jButtonCancelarUsuario.setEnabled(false);
        jButtonCancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarUsuarioActionPerformed(evt);
            }
        });

        jButtonAlterarUsuario.setText("Alterar");
        jButtonAlterarUsuario.setEnabled(false);
        jButtonAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarUsuarioActionPerformed(evt);
            }
        });

        jButtonExcluirUsuario.setText("Excluir");
        jButtonExcluirUsuario.setEnabled(false);
        jButtonExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirUsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome:");

        jLabel3.setText("Usuário:");

        jLabel4.setText("Senha:");

        jTextFieldNomeUsuario.setEnabled(false);

        jTextFieldLoginUsuario.setEnabled(false);

        jPasswordSenha.setEnabled(false);

        jLabel5.setText("Confirmar senha:");

        jPasswordFieldConfirmaSenha.setEnabled(false);

        jButtonBuscarUsuario.setText("Buscar");
        jButtonBuscarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarUsuarioActionPerformed(evt);
            }
        });

        jLabel6.setText("ID:");

        jTextFieldIdUsuario.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonExcluirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCancelarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonNovoUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalvarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAlterarUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordFieldConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscarUsuario))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeUsuario)
                            .addComponent(jTextFieldLoginUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonNovoUsuario))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonSalvarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterarUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluirUsuario))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(29, 29, 29))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(41, 41, 41)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextFieldLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(29, 29, 29))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(29, 29, 29))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordFieldConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarUsuario))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Cadastro de Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        setSize(new java.awt.Dimension(521, 388));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoUsuarioActionPerformed
        flag = 1;
        jTextFieldNomeUsuario.setEnabled(true);
        jTextFieldLoginUsuario.setEnabled(true);
        jPasswordSenha.setEnabled(true);
        jPasswordFieldConfirmaSenha.setEnabled(true);
        jButtonSalvarUsuario.setEnabled(true);
        jButtonCancelarUsuario.setEnabled(true);
        jTextFieldBuscarUsuario.setEnabled(false);
        jButtonBuscarUsuario.setEnabled(false);
        jButtonNovoUsuario.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoUsuarioActionPerformed

    private void jButtonSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarUsuarioActionPerformed
        mod.setPesquisa(jTextFieldLoginUsuario.getText());
        ModeloUsuario usuario = control.verificaLogin(mod);
        if (jTextFieldNomeUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Nome para continuar");
            jTextFieldNomeUsuario.requestFocus();
        }else if (jTextFieldLoginUsuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha o Usuário para continuar");
            jTextFieldLoginUsuario.requestFocus();
        }else if (usuario != null){
            JOptionPane.showMessageDialog(null, "Usuário não disponível");
            jTextFieldLoginUsuario.requestFocus();
        }else if (jPasswordSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Preencha a Senha para continuar");
            jPasswordSenha.requestFocus();
        }else if(jPasswordSenha.getText().equals(jPasswordFieldConfirmaSenha.getText())){
            if (flag == 1){
            mod.setNome(jTextFieldNomeUsuario.getText());
            mod.setLogin(jTextFieldLoginUsuario.getText());
            mod.setSenha(jPasswordSenha.getText());
            control.salvar(mod);
            jTextFieldNomeUsuario.setText("");
            jTextFieldLoginUsuario.setText("");
            jPasswordSenha.setText("");
            jPasswordFieldConfirmaSenha.setText("");
            jTextFieldNomeUsuario.setEnabled(false);
            jTextFieldLoginUsuario.setEnabled(false);
            jPasswordSenha.setEnabled(false);
            jPasswordFieldConfirmaSenha.setEnabled(false);
            jButtonSalvarUsuario.setEnabled(false);
            jButtonCancelarUsuario.setEnabled(false);
            jButtonAlterarUsuario.setEnabled(false);
            jButtonExcluirUsuario.setEnabled(false);
            jTextFieldBuscarUsuario.setEnabled(true);
            jButtonBuscarUsuario.setEnabled(true);
        }else{
            mod.setIdUsuario(Integer.parseInt(jTextFieldIdUsuario.getText()));
            mod.setNome(jTextFieldNomeUsuario.getText());
            mod.setLogin(jTextFieldLoginUsuario.getText());
            mod.setSenha(jPasswordSenha.getText());
            control.editar(mod);
            jTextFieldNomeUsuario.setText("");
            jTextFieldLoginUsuario.setText("");
            jPasswordSenha.setText("");
            jPasswordFieldConfirmaSenha.setText("");
            jTextFieldNomeUsuario.setEnabled(false);
            jTextFieldLoginUsuario.setEnabled(false);
            jPasswordSenha.setEnabled(false);
            jPasswordFieldConfirmaSenha.setEnabled(false);
            jButtonSalvarUsuario.setEnabled(false);
            jButtonCancelarUsuario.setEnabled(false);
            jButtonNovoUsuario.setEnabled(true);
            jTextFieldBuscarUsuario.setEnabled(true);
            jButtonBuscarUsuario.setEnabled(true);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Senha e Confirmar senha devem ser iguais");
        }
    }//GEN-LAST:event_jButtonSalvarUsuarioActionPerformed

    private void jButtonCancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarUsuarioActionPerformed
        jTextFieldNomeUsuario.setEnabled(!true);
        jTextFieldLoginUsuario.setEnabled(!true);
        jPasswordSenha.setEnabled(!true);
        jPasswordFieldConfirmaSenha.setEnabled(!true);
        jButtonSalvarUsuario.setEnabled(!true);
        jButtonCancelarUsuario.setEnabled(!true);
        jButtonNovoUsuario.setEnabled(true);
        jButtonAlterarUsuario.setEnabled(false);
        jButtonExcluirUsuario.setEnabled(false);
        jTextFieldBuscarUsuario.setEnabled(true);
        jButtonBuscarUsuario.setEnabled(true);
        jTextFieldNomeUsuario.setText("");
        jTextFieldLoginUsuario.setText("");
        jTextFieldIdUsuario.setText("");
        jPasswordSenha.setText("");
        jPasswordFieldConfirmaSenha.setText("");
    }//GEN-LAST:event_jButtonCancelarUsuarioActionPerformed

    private void jButtonAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarUsuarioActionPerformed
        flag = 2;
        jTextFieldNomeUsuario.setEnabled(true);
        jTextFieldLoginUsuario.setEnabled(true);
        jPasswordSenha.setEnabled(true);
        jPasswordFieldConfirmaSenha.setEnabled(true);
        jButtonSalvarUsuario.setEnabled(true);
        jButtonCancelarUsuario.setEnabled(true);
        jButtonAlterarUsuario.setEnabled(false);
        jButtonNovoUsuario.setEnabled(false);
        jButtonExcluirUsuario.setEnabled(false);
    }//GEN-LAST:event_jButtonAlterarUsuarioActionPerformed

    private void jButtonExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirUsuarioActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");
        if (resposta == JOptionPane.YES_OPTION){
            mod.setIdUsuario(Integer.parseInt(jTextFieldIdUsuario.getText()));
            control.excluir(mod);
            jTextFieldNomeUsuario.setText("");
            jTextFieldNomeUsuario.setEnabled(false);
            jTextFieldLoginUsuario.setText("");
            jTextFieldLoginUsuario.setEnabled(false);
            jButtonSalvarUsuario.setEnabled(false);
            jButtonCancelarUsuario.setEnabled(false);
            jButtonNovoUsuario.setEnabled(true);
            jTextFieldIdUsuario.setText("");
            jButtonAlterarUsuario.setEnabled(false);
            jButtonExcluirUsuario.setEnabled(false);
            jTextFieldBuscarUsuario.setEnabled(true);
            jButtonBuscarUsuario.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonExcluirUsuarioActionPerformed

    private void jButtonBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarUsuarioActionPerformed
        mod.setPesquisa(jTextFieldBuscarUsuario.getText());
        ModeloUsuario usuario = control.buscaUsuario(mod);
        if (usuario == null){
            jTextFieldBuscarUsuario.setText("");
        }else{
            jTextFieldNomeUsuario.setText(usuario.getNome());
            jTextFieldLoginUsuario.setText(usuario.getLogin());
            jTextFieldIdUsuario.setText(String.valueOf(usuario.getIdUsuario()));
            jButtonAlterarUsuario.setEnabled(true);
            jButtonExcluirUsuario.setEnabled(true);
            jTextFieldBuscarUsuario.setText("");
        }
    }//GEN-LAST:event_jButtonBuscarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarUsuario;
    private javax.swing.JButton jButtonBuscarUsuario;
    private javax.swing.JButton jButtonCancelarUsuario;
    private javax.swing.JButton jButtonExcluirUsuario;
    private javax.swing.JButton jButtonNovoUsuario;
    private javax.swing.JButton jButtonSalvarUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldConfirmaSenha;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JTextField jTextFieldBuscarUsuario;
    private javax.swing.JTextField jTextFieldIdUsuario;
    private javax.swing.JTextField jTextFieldLoginUsuario;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
