/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import controle.ConexaoBD;
import java.awt.Color;

/**
 *
 * @author Antonio
 */
public class TelaPrincipal extends javax.swing.JFrame {

    ConexaoBD conecta = new ConexaoBD();
    public TelaPrincipal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jButtonDrone01 = new javax.swing.JButton();
        jButtonDrone02 = new javax.swing.JButton();
        jPanelOpcoes = new javax.swing.JPanel();
        jLabelTemperatura = new javax.swing.JLabel();
        jTextFieldTemperatura = new javax.swing.JTextField();
        jLabelUmidade = new javax.swing.JLabel();
        jTextFieldUmidade = new javax.swing.JTextField();
        jButtonCalcular = new javax.swing.JButton();
        jTextFieldResultado = new javax.swing.JTextField();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuDrone = new javax.swing.JMenu();
        jMenuItemCadastroDrone = new javax.swing.JMenuItem();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemCadastroUsuario = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrame1.setTitle("Bem-Vindo");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jButtonDrone01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconDrone.png"))); // NOI18N
        jButtonDrone01.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jButtonDrone01ComponentShown(evt);
            }
        });
        jButtonDrone01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrone01ActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonDrone01);
        jButtonDrone01.setBounds(20, 10, 160, 80);

        jButtonDrone02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/iconDrone.png"))); // NOI18N
        jButtonDrone02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDrone02ActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonDrone02);
        jButtonDrone02.setBounds(20, 100, 160, 80);

        jPanelOpcoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTemperatura.setText("Temperatura Local:");

        jTextFieldTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTemperaturaActionPerformed(evt);
            }
        });

        jLabelUmidade.setText("Umidade do Ar:");

        jTextFieldUmidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUmidadeActionPerformed(evt);
            }
        });

        jButtonCalcular.setText("Calcular");
        jButtonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelOpcoesLayout = new javax.swing.GroupLayout(jPanelOpcoes);
        jPanelOpcoes.setLayout(jPanelOpcoesLayout);
        jPanelOpcoesLayout.setHorizontalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTemperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                        .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTemperatura)
                            .addComponent(jTextFieldUmidade, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelOpcoesLayout.setVerticalGroup(
            jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOpcoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUmidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanelOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanelInternal.add(jPanelOpcoes);
        jPanelOpcoes.setBounds(260, 10, 300, 170);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FUNDO-AZUL-CLARO.jpg"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 0, 630, 210);

        jInternalFrame1.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 40, 630, 210);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Sistema de Prevenção de Incêndio Florestal");
        jInternalFrame1.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 400, 20);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(0, 70, 650, 280);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imagens-imagens-para-fundo-6.jpg"))); // NOI18N
        jLabelFundoPrincipal.setText("jLabel1");
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 650, 350);

        jMenuDrone.setText("Drone");

        jMenuItemCadastroDrone.setText("Cadastro de Drone");
        jMenuItemCadastroDrone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroDroneActionPerformed(evt);
            }
        });
        jMenuDrone.add(jMenuItemCadastroDrone);

        jMenuBar1.add(jMenuDrone);

        jMenuUsuarios.setText("Usuarios");

        jMenuItemCadastroUsuario.setText("Cadastro de Usuário");
        jMenuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemCadastroUsuario);

        jMenuBar1.add(jMenuUsuarios);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(667, 409));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void limpaCampos(){
        jTextFieldTemperatura.setText("");
        jTextFieldUmidade.setText("");
        jTextFieldResultado.setText("");
    }
    
    public void calculaRisco(Double temperatura){
        if (temperatura < 50){
            jTextFieldResultado.setText("Sem risco de incêndio");
            jTextFieldResultado.setBackground(Color.GREEN);
            jTextFieldResultado.setForeground(Color.BLACK);
        } else if (temperatura >= 50 && temperatura < 70){
            jTextFieldResultado.setText("Baixo risco de incêndio");
            jTextFieldResultado.setBackground(Color.YELLOW);
            jTextFieldResultado.setForeground(Color.BLACK);
        } else if (temperatura >= 70 && temperatura < 90){
            jTextFieldResultado.setText("Alto risco de incêndio");
            jTextFieldResultado.setBackground(Color.ORANGE);
            jTextFieldResultado.setForeground(Color.BLACK);
        } else{
            jTextFieldResultado.setText("Alerta máximo de incêndio");
            jTextFieldResultado.setBackground(Color.RED);
            jTextFieldResultado.setForeground(Color.BLACK);
        }
    }
    
    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        conecta.desconecta();
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButtonDrone01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrone01ActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        jTextFieldResultado.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonDrone01ActionPerformed

    private void jButtonDrone02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDrone02ActionPerformed
        // TODO add your handling code here:
        limpaCampos();
        jTextFieldResultado.setBackground(Color.WHITE);
    }//GEN-LAST:event_jButtonDrone02ActionPerformed

    private void jTextFieldTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTemperaturaActionPerformed

    private void jTextFieldUmidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUmidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUmidadeActionPerformed

    private void jButtonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularActionPerformed
        // TODO add your handling code here:
        Double temperatura = Double.parseDouble(jTextFieldTemperatura.getText());
        Integer umidade = Integer.parseInt(jTextFieldUmidade.getText());
        calculaRisco(temperatura);
    }//GEN-LAST:event_jButtonCalcularActionPerformed

    private void jButtonDrone01ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jButtonDrone01ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDrone01ComponentShown

    private void jMenuItemCadastroDroneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroDroneActionPerformed
        FormDrone cadastroDrone = new FormDrone();
        cadastroDrone.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroDroneActionPerformed

    private void jMenuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroUsuarioActionPerformed
        FormUsuario cadastroUsuario = new FormUsuario();
        cadastroUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcular;
    private javax.swing.JButton jButtonDrone01;
    private javax.swing.JButton jButtonDrone02;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelTemperatura;
    private javax.swing.JLabel jLabelUmidade;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuDrone;
    private javax.swing.JMenuItem jMenuItemCadastroDrone;
    private javax.swing.JMenuItem jMenuItemCadastroUsuario;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JPanel jPanelInternal;
    private javax.swing.JPanel jPanelOpcoes;
    private javax.swing.JTextField jTextFieldResultado;
    private javax.swing.JTextField jTextFieldTemperatura;
    private javax.swing.JTextField jTextFieldUmidade;
    // End of variables declaration//GEN-END:variables
}
